### ISSUE TITLE
Wait on srv.NextActions after creating server

### ISSUE THREAD

**Issue by apricote** [JonasProgrammer/docker-machine-driver-hetzner#119]
Julian from @hetznercloud here :wave: 

while investigating a customer ticket, I noticed that you are not waiting on the additional actions returned from the `POST /v1/servers` endpoint. Instead you poll the server to wait for it to startup. 

https://github.com/JonasProgrammer/docker-machine-driver-hetzner/blob/54b321f1016b4e07a291c3e01525061d5a47655a/driver/driver.go#L500-L511

I would recommend you wait on the actions in [`srv.NextActions`](https://pkg.go.dev/github.com/hetznercloud/hcloud-go/v2/hcloud#ServerCreateResult). In there is also the `start_server` action, which is marked as completed once the server is running. You can check out our CLI code for comparison: https://github.com/hetznercloud/cli/blob/50fe4ca15deea739279539cf0bb2628ee2693f0e/internal/cmd/server/create.go#L100-L110

There is also a helper [client.Action.WatchOverallProgress](https://pkg.go.dev/github.com/hetznercloud/hcloud-go/v2/hcloud#ActionClient.WatchOverallProgress) that can watch multiple actions at the same time.

Based on the contents, the `GET /v1/servers/:id` endpoint which you currently use is less efficient than simply polling the actions. It also counts towards a different Rate Limit budget, which caused an issue for one customer because they exhausted the normal Rate Limit with these calls.

**Comment by JonasProgrammer** [comment]
Hi Julian,

thanks a lot for the input, I'll look into fixing this. Unfortunately, the way this currently works is yet another left-over from pre-`hcloud-go` times...

While I will provide a bug-fix release for this issue, I now seriously do consider re-implementing the whole creation logic at some point. Too many issues caused by the driver still basically doing what it has done since cloud-beta times with some more features and `waitForActions` sprinkled across. If there is any more input you want to share, I'd be glad to hear it.

**Comment by apricote** [comment]
Awesome! Thanks for the quick improvement :) 

I used to be a user of the project myself back in 2018-2020, its nice to see you still work on this after all these years!

**Comment by Wouter0100** [comment]
Thanks for the investigation, @apricote - and for the quick implementation of the suggested changes @JonasProgrammer!

I _think_ we were the customer you were investigating for @apricote, and we now updated this docker-machine driver to ensure we won't hit any limits again :-).
