### ISSUE TITLE
Error starting plugin binary

### ISSUE THREAD

**Issue by danieljuhl** [JonasProgrammer/docker-machine-driver-hetzner#23]
I get the following error using docker-machine v0.15.0: `Error starting plugin binary: fork/exec /usr/local/bin/docker-machine-driver-hetzner: exec format error`

Is there any known issues with these versions?

**Comment by JonasProgrammer** [comment]
Which operating system and architecture are you on?

**Comment by danieljuhl** [comment]
macOS Mojave on a MacBook Pro (2,7 GHz Intel Core i7)

**Comment by JonasProgrammer** [comment]
Well, that makes things a little more complicated, because I only have Linux and Windows machines available for testing. The closest I ever get to running it on OSX is `gox` producing something on Travis.

Could you maybe try an older release, such as 1.0.0? If that does not work either, we will have to further investigate what our Travis build actually produces. On the other hand, if it works, I will try and trigger a rebuild of 1.2.0.

Sorry for the inconvenience.

**Comment by mxschmitt** [comment]
Hello,
which binary have you choosen? Linux/amd64?
https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/1.2.0/docker-machine-driver-hetzner_1.2.0_linux_amd64.tar.gz

**Comment by danieljuhl** [comment]
@mxschmitt yes! Sorry.. I copy-paste the instructions from the README.md without noticing the clear message about the example using the linux build.

**Comment by Micromegass** [comment]
@danieljuhl Did you get this working for mac? If so, could you be so kind telling me which image you used to get this working? Thanks!

**Comment by JonasProgrammer** [comment]
Not a mac user, but the released binaries labeled `darwin` should do, so depending on your architecture either the [32 bit](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.0.1/docker-machine-driver-hetzner_2.0.1_darwin_386.tar.gz) or the [64 bit](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/2.0.1/docker-machine-driver-hetzner_2.0.1_darwin_amd64.tar.gz) version.

**Comment by Micromegass** [comment]
Thank you @JonasProgrammer! I got it to work with the darwin version. Thanks so much for the help and thanks for providing this fantastic tool! Works like a charm, really great!
