### ISSUE TITLE
Time between requests to prevent Hetzner Rate Limit

### ISSUE THREAD

**Issue by maxfriedmann** [JonasProgrammer/docker-machine-driver-hetzner#71]
At first: Many thanks for this great docker machine driver. 

We've been using it for a week in testing, without any issues. Today we started using it in production and ran into the rate limits of hetzner itself. It seems like if you once hit the rate limit, you'll never get out of that situation since the machine driver keeps on retrying all requests in an endless loop.

Would it be possible to implement a cool down time when 429 errors happened? 

Unfortunately I am not a Go Programmer :/

**Comment by maxfriedmann** [comment]
The actual error from the driver is 
`ERROR: Error creating machine: Error in driver during machine creation: could not create server: we are unable to provision servers for this location, try with a different location or try later (resource_unavailable) driver=hetzner`

I am not sure if the rate limiting is the consequence of the driver retrying to create machines or vice versa.

**Comment by maxfriedmann** [comment]
Unfortunately we had to move back to root servers since the performance of the cloud servers wasn't satisfying. Thanks for your support!

**Comment by JonasProgrammer** [comment]
> 
> 
> Unfortunately we had to move back to root servers since the performance of the cloud servers wasn't satisfying. Thanks for your support!

Sorry to hear that but thank you for taking the time to come back and close this. Perhaps this could still be implemented in the future, but wrapping every operation in a retry-loop (and maintaining a consistent internal state) turned out to be harder than I initially anticipated, especially with cleanup stuff. I will keep a mental note, but with your initial issue being an external problem, I don't think the benefit outweighs the additional complexity brought in.

Still glad, you found something working for you in the end, even if it turned out to be the good old bare metal.
