### ISSUE TITLE
Support for "PLACEMENT GROUPS"

### ISSUE THREAD

**Issue by anebi** [JonasProgrammer/docker-machine-driver-hetzner#72]
Hello,

Hetzner has relelased a new functionality called "PLACEMENT GROUPS" and I believe that this functionality is very important for Cluster HA setups and stability. It would be great if machine driver adds support for it and even use it by default creating a placement group then attach the nodes to that group.

Thanks and regards,
Ali Nebi

**Comment by anebi** [comment]
Hi,

I didn't give much thinking on the best way of dealing with the placement groups and how the process should go. I am OK with any solution you could provide actually. I thought that default behaviour of placing nodes into a placing group would be good from stability point no matter of the environment or how many clusters are deployed.

When i think now, in reallity we don't really need placement group per cluster, because a single placement group should be more than enough for all machines that require spreading.

So what we could have maybe is to have a flag that will define if we want to use a  placement group or not, and then if there are existing groups to have a list where we can select which one to be used, or if there is no existing group then to create one.

In any case, any solution is ok for me. I don't have any special requirements to be honest :)

Thanks and regards,
Ali

**Comment by anebi** [comment]
Hi,

Thank you for fast implementation. I did some tests for both functionalities:
    - autocreating of the placement group and getting the instances assigned to that group - worked fine
    - assigning a new instance to existing group - worked fine

What i noticed is that the autocreated placement group didn't get removed automarically once the last instance was removed/deleted using the docker-machine (stop & rm). This is the only thing that might require an extra check. Of course, only if you want to auto delete that autocreated group.

Otherwise looks fine to me.

Thanks again and best regards,
Ali Nebi

**Comment by JonasProgrammer** [comment]
Hi,

thanks for testing this so quickly. I tried to reproduce your issue, but I think the root cause here was a timing problem: When you kill `docker-machine` too early in the creation process and try to remove the server, it seems sometimes the placement group information is either missing or outdated.

I did manage to reproduce it once, but with some time between creation/deletion and deletions of different machines, everything worked as expected. I'm not entirely sure how to approach this; simply adding some sleeps in the hopes of getting the timing right seems hacky to me.

If that is not a major concern, I'd merge for now as-is, especially with placement groups being free of charge. Should that change in the future, this may need further addressing.

Best regards
Jonas
