### ISSUE TITLE
Upgrades in place?

### ISSUE THREAD

**Issue by onpaws** [JonasProgrammer/docker-machine-driver-hetzner#78]
Hi,
Thanks for your efforts with `docker-machine-driver-hetzner`, it's been helpful to me for setting things up on Hetzner.

I was curious about upgrades. Almost 2 years ago we installed version [2.1.0](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/tag/2.1.0) on a Rancher instance. These days it seems like [3.7.0](https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/tag/3.7.0) is the current release.

IIUC Rancher may support a way to upgrade 'node drivers' in place. 
<img width="1108" alt="image" src="https://user-images.githubusercontent.com/182515/150959555-74b97e99-607d-41a5-ad85-6e78ac2f1acf.png">

Or, I could add v3.7.0 as a new one.
I was wondering what I might expect if I upgrade the plugin in-place, and try to mutate something about an existing VM?
Are releases backwards compatible?

Thank you

**Comment by JonasProgrammer** [comment]
Hi,

in theory there should not be any problems -- the major version bump was due to a changed default image after Hetzner rotated its supported images for machine creation. Other than that, while some internal stuff changed, both the external file format and the driver ABI itself should be perfectly backwards-compatible. On the other hand, I don't want to make any guarantees that might not hold due to an oversight.

If you want to make sure, just try and create a machine manually with the 2.1.0 build and then try interacting with it using the newer driver. Given some basic `docker-machine` functionality, such as starting, stopping, and perhaps SSH for good measure work, I think that it should be safe to assume Rancher works as well.

I'd be glad if you could report back, whether it worked and about any problems encountered, if any!
