### ISSUE TITLE
[BUG] Server doesn't start automatically

### ISSUE THREAD

**Issue by zek** [JonasProgrammer/docker-machine-driver-hetzner#81]
Hello,

When I set networks by `HETZNER_NETWORKS` env variable, after the server created it doesn't start automatically. 
I had to start it manually throught hetzner panel.

**Comment by JonasProgrammer** [comment]
Hi,

sorry for the inconvenience. This seems rather odd... building the network config should not affect the server creation whatsoever. The network IDs to be added are gathered beforehand and then given to the `CreateServer` call -- so given the order of operation, there should be no impact.
There is an optional [flag](https://docs.hetzner.cloud/#servers-create-a-server) indicating whether the server should be started or not, but it defaults to true and we never set it in the past.

Could you maybe try creating a server connected to an existing net with the official `hcloud` tool and see if it behaves differently? Right now I fail to see how the driver code would cause the behaviour you described, but perhaps I'm overlooking something.

**Comment by zek** [comment]
Hey thanks for quick response,

```
hcloud server create  --name test --image "ubuntu-20.04" --type cx11 --network "my-network"
```

I tested it out and server started without any problem.

<img width="1297" alt="image" src="https://user-images.githubusercontent.com/3463291/163573630-7f6a3766-c3f6-4a68-8629-c0d982709428.png">




With docker-machine-driver-hetzner, I had to start it on hetzner panel

<img width="1267" alt="image" src="https://user-images.githubusercontent.com/3463291/163573675-5a10917f-5d6f-48c5-8e23-374c6ca7e1d9.png">

**Comment by JonasProgrammer** [comment]
Very strange indeed. I just tried with a fresh test project and for me everything works as expected (though I had to specify at least one network via command line argument instead of the environment variable due to an unrelated bug #37). It worked with both a single network provided via command line, as well as two -- one of which was provided via environment variable.

The only thing I could see in the cloud panel was that the server sometimes did take a little more time after creation, before it actually spun up... but still, it was like under a minute between creation and automatic start.

Anyways, as I'm currently out of ideas, I have just released 3.7.1 with updated dependencies. I was unable to reproduce the problem with neither a 3.7.0 build downloaded from GitHub nor my local 3.7.1 build. But maybe you can give it a shot so we can strike outdated library versions from the list of possible causes.

**Comment by zek** [comment]
Thank you so much
I found the problem. I had networks definition both on env and argument. I removed the HETZNER_NETWORKS from the env.
Somehow they're colliding with each other.

**Comment by JonasProgrammer** [comment]
Glad you were able to figure it out. If it is indeed the same network being specified more than once that causes the issue, I think that is a bug on the API side of things. I'll do a few experiments tomorrow and if that indeed causes the issue and perhaps file a ticket with Hetzner.

**Comment by JonasProgrammer** [comment]
@zek Just to let you know, your suffering was not pointless; the underlying issue is fixed now. hetznercloud/hcloud-go#196
