### ISSUE TITLE
Support the creation of servers with chosen primary ip or random primary ip

### ISSUE THREAD

**Issue by ItsReddi** [JonasProgrammer/docker-machine-driver-hetzner#88]
It would be nice to have the ability to choose a primary ip while creating a node.
As it would help to recreate nodes while keeping the ip address.

For example useful for mail-server nodes.

As addition it would be nice for an options use any free random primary if not specific primary was specified.

**Comment by JonasProgrammer** [comment]
Hi and thanks for the suggestion.

Since the feature to keep IPs was not around when the driver was originally designed, I will have to poke around on how this could be achieved. Choosing a specific IP should not be a problem, provided the API support is there.

I'm undecided regarding the 'choose a random reserved address'-thing, however. While I do see how it might be useful in certain scenarios, I think the 'need specific IP' use case is much more common -- e.g. due to configured remote sites. If this functionality is truly needed, it should be a one-liner on bash/posh, provided `hcloud` is available, for the driver it is out-of-scope IMHO.

One thing I would be interested in: Do you have any suggestions on handling server deletion? As of now primary IPs should be released, as is the default behaviour on server deletion. Would an additional flag `--hetzner-keep-primary[=true|false]` be useful? With it defaulting to true on the specified primary case?

**Comment by JonasProgrammer** [comment]
So I came around to have a look at this: Primary IPs can be resolved both by name and address value, so this should not be a problem.

The addresses can have certain flags specifying whether they are protect or 'recyclable', i.e. they would be deleted on server deletion. If a new primary address is implicitly created during server creation, however, there seems to be no way to specify this flag. From this I assume the 'recylce' flag is always set for those IPs unless manually changed after creation.

I don't really think sophisticated address handling should be part of the driver, so implementing post-creation procedures to update this stuff seems rather out-of-scope to me.

Would it still be feasible if you can just specify existing IPs (either by name or address) and keep whatever is set on implicit creation? A user can still update the primary IP (object) after creation using the web frontend or CLI if they so desire.

**Comment by ItsReddi** [comment]
sounds good to me

**Comment by JonasProgrammer** [comment]
Should work in 3.9.2.

Sorry it took me so long, I introduced a bug and never actually checked what was being passed to hetzner before working on #90 :<

**Comment by ItsReddi** [comment]
No pressure at all. Thanks for your work! 👍
