### ISSUE TITLE
No UI in Rancher after 3.8.1

### ISSUE THREAD

**Issue by smirnov-mi** [JonasProgrammer/docker-machine-driver-hetzner#96]
I'm using Hetzner Node Driver since v. 3.7.1 I think, in the Rancher (v2.5x -- 2.7.1 now).
Node driver is configured as foll.:

Download URL: https://github.com/JonasProgrammer/docker-machine-driver-hetzner/releases/download/3.7.1/docker-machine-driver-hetzner_3.7.1_linux_amd64.tar.gz
Custom UI URL: https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js
Whitelist Domains: storage.googleapis.com

This version has been working well for two years now. By working I mean "manual" creation of the cluster, adding and removing nodes, using rancher web-interface.

As I tried to setup a new version of the Hetzner Node Driver, usind v3.10.0, I can't see any errors during the setup, however I'm unable to create a new cluster, as the whole block with the nodes is missing on the cluster creation web-page. Node Driver's name is changed to "Hetzner_instrumented" to, btw.

The error occurs in the driver versions above 3.8.1. 3.9.0 3.9.2 3.10.0 all show the same behaviour. I tried to look up for an updated version of the UI (https://storage.googleapis.com/hcloud-rancher-v2-ui-driver/component.js) with no luck. Maybe I shuold log this issue on the UI page, not sure.   
https://github.com/mxschmitt/ui-driver-hetzner

**Comment by JonasProgrammer** [comment]
Hi,

I have no experience with ranger. The glue code for the web interface is another piece of the puzzle, the driver binary itself performs fine, as expected.

> Node Driver's name is changed to "Hetzner_instrumented" to[o], btw.

Yes and no, the driver name hasn't changed, I have just packaged an additional binary for convenience. Vanilla docker machine users can use `-d hetzner_instrumented` rather than `-d hetzner` to get a driver binary producing much more debug output (potentially leaking confident information -- hence this is not in the normal binary), so I thought it would be helpful to have that built as-is.
However, now seeing two issues (#94 and this) about the very same issue, I guess we cannot have nice things and I have to remove that config from the release builds. `Go-releaser` won't let me package them as separate archives either, as they deem two archives per architecture too confusing...

**Comment by smirnov-mi** [comment]
I understand. I will try to get in touch with UI developers

**Comment by smirnov-mi** [comment]
FYI:  i'm running rancher 2.7.2-rc2 now and I just upgraded the Hetzner driver to 3.11.0 , everything works fine now.
