### ISSUE TITLE
Suggestion: `--hetzner-user-data-from-file` could be string instead of boolean

### ISSUE THREAD

**Issue by perlun** [JonasProgrammer/docker-machine-driver-hetzner#99]
Hi,

Thanks for a great tool. :pray: Currently setting it up for usage with the GitLab Autoscaler (which still uses Docker Machine, despite the deprecation upstream).

One question though:

```
   --hetzner-user-data 											Cloud-init based User data [$HETZNER_USER_DATA]
   --hetzner-user-data-from-file									Cloud-init based User data is file [$HETZNER_USER_DATA_FROM_FILE]
```

I presumed (incorrectly) that `--hetzner-user-data-from-file` was a string, which it isn't; it's a boolean flag intended to be used _together_ with the `--hetzner-user-data`. Would it make sense to change this so that `--hetzner-user-data-from-file` could be used on its own, perhaps something like `--hetzner-user-data-file /path/to/file`? :thinking: Just trying to see if we could make it slightly easier/more natural-seeming for such scenarios.

**Comment by JonasProgrammer** [comment]
After some thinking, I unfortunately think there is not really a good way to re-purpose the flag in the way you suggested. Mainly because boolean flags have an implied value of `true` if passed without an option value, but no such thing exists for string flags -- i.e. changing `--hetzner-user-data-from-file` to string would cause currently-valid command line calls to become invalid.

Adding a new option, such as `--hetzner-user-data-file`, with the implied semantics is the only way I see to tackle this. But that in turn would have to be mutually-exclusive with the existing flags. Given that the original issue is about their semantics being confusing, I'm not entirely sure this would do any good.

**Comment by perlun** [comment]
> Adding a new option, such as `--hetzner-user-data-file`, with the implied semantics is the only way I see to tackle this. But that in turn would have to be mutually-exclusive with the existing flags. Given that the original issue is about their semantics being confusing, I'm not entirely sure this would do any good.

I think this sounds like a good way forward. :+1: 

1. Add the new flag.
2. Deprecate the old flag.
3. At some point (version 4.x or some other future major version), drop the existing flag. Make this very clear in the release notes to avoid making users confusing.

**Comment by perlun** [comment]
Thanks @JonasProgrammer, appreciated! ❤️
